# NumPy:基本操作

[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/rsimd/NITIC-HandsOnDeepLearning/blob/main/notebooks/numpy_basic_functions.ipynb)

## np.arrayの使い方

### np.arrayの作り方

`np.array`関数にリスト型オブジェクトを渡すと配列が作成できます．

In [2]:
import numpy as np

def object_checker(obj):
    print("型：",type(obj))
    print("中身：",obj)
    if isinstance(obj, np.ndarray):
        print("行列のshape：",obj.shape)

In [3]:
list1 = [1,2,3]
object_checker(list1)

型： <class 'list'>
中身： [1, 2, 3]


In [4]:
arr1 = np.array(list1)
object_checker(arr1)

型： <class 'numpy.ndarray'>
中身： [1 2 3]
行列のshape： (3,)


In [5]:
list2 = [[1,2,3], [4,5,6]]
arr2 = np.array(list2)
object_checker(arr2)

型： <class 'numpy.ndarray'>
中身： [[1 2 3]
 [4 5 6]]
行列のshape： (2, 3)


### numpy関数によるnp.ndarrayの初期化
numpyはPythonに配列(np.ndarray)を提供します。  
このnp.arrayはリストやtupleを元に作るだけでなく、np.zeros、np.onesなどの関数からも作ることができます。

#### 【問題１】 np.zerosを使って要素数10の配列を作ってください。

#### 【問題２】 np.onesを使ってshape (10,5)の行列を作ってください。

#### 【問題３】 np.arangeを使って0～9までの値を持ったベクトルを作ってください。  

___hint: np.arangeはrangeとほぼ同様の動作をします。___

#### np.arrayのshapeの変更

np.arrayはデータを効率的に扱うために、numpyの関数だけで配列の形を変形する事ができます。

もっとも代表的な方法として、np.reshapeがあります。

In [6]:
arr3 = np.arange(20)
arr4 = np.reshape(arr3, (10,2)) # arr3.reshape((10,2))でも可

print(
    "オリジナル：\n",arr3,
    "\nreshape後：\n",arr4
)

オリジナル：
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 
reshape後：
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


#### 【問題４】 ゼロで初期化した要素数30の配列を、5x2x3の三階テンソルに変換してください。

#### 行列の転置

In [7]:
arr5 = arr4.T
arr5

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

## np.ndarrayの演算
numpy.ndarrayは高速な行列演算が可能です。

また、計算の結果は尤もらしい型になります。  

arr1の要素はint32ですが、1.0などのfloat64と演算する事で、計算結果result1がfloat64として出力されます。

#### 加算

In [8]:
print(result1 := arr1 +1.0)
# result1 = arr1 + 1.0
# print(result1) 
# を省略して書くと print(result1 := arr1 +1.0) になる
print("arr1.dtype:",arr1.dtype)
print("result1.dtype:", result1.dtype)

[2. 3. 4.]
arr1.dtype: int64
result1.dtype: float64


#### 減算

In [9]:
print(result2 := result1 - 5.0)

[-3. -2. -1.]


#### 乗算

In [10]:
print(result3 := result2 * 1.5)

[-4.5 -3.  -1.5]


#### 除算

In [11]:
print(result4 := result3 / 3.0)

[-1.5 -1.  -0.5]


#### 剰余

In [12]:
print(result5 := result4 % 2)

[0.5 1.  1.5]


#### 【問題】`result5`の各要素を3乗してみよう．

#### 等式

In [13]:
print(result6 := result5 ==1)

[False  True False]


#### 不等式

In [14]:
print(result7 := result5 !=1)

[ True False  True]


In [15]:
print(result8 := result5 >=1)

[False  True  True]


In [16]:
print(result9 := result5 <1)

[ True False False]


#### 要素が含まれているか確認する

In [17]:
1 in result5

True

In [18]:
2 in result5

False

In [19]:
1 not in result5

False

In [20]:
2 not in result5

True

#### 【問題５】  以下の1～5までの処理をして答えを返す関数を作成して、実行してください。

1. 1～20までの要素を持ったベクトルを用意
2. ベクトルをreshapeし2x10行列に変換
3. 配列の各要素を20倍
4. 配列の各要素のmod 3をとる
5. 配列の0をTrue、それ以外をFalseに変換
6. 5の答えをreturn

### 配列同士の演算

配列同士の演算も、普通の演算子（+,-,\*,/,%など)でできます。

#### 加算

In [21]:
np.ones((10,5)) + np.arange(50).reshape((10,5))

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35.],
       [36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45.],
       [46., 47., 48., 49., 50.]])

#### 減算

In [22]:
np.array([10,9,8]) - np.ones(3)

array([9., 8., 7.])

#### 乗算

In [23]:
np.array([[10,9,8],[11,91,81]]) * np.array([2,3,4])

array([[ 20,  27,  32],
       [ 22, 273, 324]])

In [24]:
np.array([[10,9,8],[11,91,81]]) * np.array([[11,91,81],[10,9,8]]) 

array([[110, 819, 648],
       [110, 819, 648]])

#### 除算

In [25]:
np.array([10,9,8]) / np.array([2,3,4])

array([5., 3., 2.])

#### 剰余

In [26]:
np.array([10,9,8]) % np.array([3,4,5])

array([1, 1, 3])

#### 【問題６】
以下の流れで演習用データを作成
1. 10~19の要素を持つベクトルを用意
2. 5x2配列にreshape 
3. これを変数xに代入
4. 15~24の要素を持つベクトルを用意
5. 5x2配列にreshape 
6. これを変数yに代入

この２つの配列に対して

(1) 加算  
(2) 減算  
(3) 乗算  
(4) 除算  
(5) 剰余  

を計算

In [27]:
# (1)



In [28]:
# (2)



In [29]:
# (3)



In [30]:
# (4)



In [31]:
# (5)



### 等式と不等式

返り値はbool値（真偽値）の配列になります。

#### 等式

In [32]:
np.array([5,7,9]) == np.array([3,7,11])

array([False,  True, False])

#### 不等式

In [33]:
np.array([5,7,9]) != np.array([3,7,11])

array([ True, False,  True])

In [34]:
np.array([5,7,9]) >= np.array([3,7,11])

array([ True,  True, False])

In [35]:
np.array([5,7,9]) < np.array([3,7,11])

array([False, False,  True])

#### 【問題７】 下の変数x,yについて

(1) 2つの変数で等しい養素をTrue, 等しくない養素をFalseにしたベクトルを出力  
(2) x以上のyの養素をTrue, 未満をFalseにしたベクトルを出力

In [36]:
x = np.array([1,2,10,20])
y = np.array([5,-1,20,10])

In [37]:
# (1)



In [38]:
# (2)



### 内積と外積

#### 内積 np.dot

In [39]:
a = np.arange(0,10).reshape((2,5))
b = np.arange(0,15).reshape((5,3))

print("a:")
print(a)
print("b:")
print(b)

np.dot(a,b)

a:
[[0 1 2 3 4]
 [5 6 7 8 9]]
b:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([[ 90, 100, 110],
       [240, 275, 310]])

#### 外積 np.outer

In [40]:
c = a[0]
d = b[0]

print("c:",c,"d:",d)

np.outer(c,d)

c: [0 1 2 3 4] d: [0 1 2]


array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6],
       [0, 4, 8]])

#### 【問題８】 ニューラルネットワークの結合重み行列Wがある。  
このWと入力行列Xの内積を取り、バイアスベクトルbを足し合わせた値を出力してください。

ただし、W,X,bは以下の値を使ってください。

In [41]:
np.random.seed(seed=1234)

# 入力データ
X = np.random.random((32, 20))

n_feature = X.shape[1]
n_hidden = 5

W = np.random.random((n_feature, n_hidden))

b = np.random.uniform(n_hidden)

## 配列自体の操作

初期化して作成した配列に対して，インデクシング，reshape，転置，値の代入（上書き），スライスなどができます．

### インデクシング（要素アクセス）

配列の要素にアクセスする方法はlistと同じです．



In [42]:
print(x := np.arange(20))
x[1]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


np.int64(1)

### Booleanマスク
元の配列と同じ形状の配列を使うことで，必要な要素だけを取り出すことができる．

In [52]:
x

array([[ 100, 1000,    2,    3,    4],
       [   5, 1000,    7,    8,    9],
       [  10, 1000,   12,   13,   14],
       [1000, 1001, 1002, 1003, 1004]])

In [55]:
mask = np.array([[True, False, False, False, False],
                 [False, True, False, False, False],
                 [False, False, True, False, False],
                 [False, False, False, True, False],]
            )
x[mask]

array([ 100, 1000,   12, 1003])

条件式を使えばブールマスクが作れる．

In [56]:
mask = x > 10
mask

array([[ True,  True, False, False, False],
       [False,  True, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [57]:
x[mask]

array([ 100, 1000, 1000, 1000,   12,   13,   14, 1000, 1001, 1002, 1003,
       1004])

つまり`[]`の中に直接条件式を書けばOK

In [58]:
x[x<100]

array([ 2,  3,  4,  5,  7,  8,  9, 10, 12, 13, 14])

### reshape

行列の形を変える

In [43]:
print(x := x.reshape((4,5)))
print("形状：", x.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
形状： (4, 5)


In [44]:
print(x2 := x.astype(np.float16))
print("型：", x2.dtype)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
型： float16


#### 【問題９】以下の処理を実装せよ．
1. 100から119までの要素を持ったベクトルaを作る
2. aを2x10行列に変形
3. aを単精度浮動小数点数にキャスト変換


#### 転置

In [45]:
print(x2 := x.T)
print("形状：", x2.shape)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
形状： (5, 4)


#### 値の代入

特定要素を置き換え

In [46]:
x2[0,0] = 100

x2

array([[100,   5,  10,  15],
       [  1,   6,  11,  16],
       [  2,   7,  12,  17],
       [  3,   8,  13,  18],
       [  4,   9,  14,  19]])

配列の1行目を全て上書き  （インデックスは0スタートであることに注意）

上書きしたい要素数と同じ要素数の配列を使えば，その通りに上書きできる．


In [47]:
x2[1] = np.arange(100,104)

x2

array([[100,   5,  10,  15],
       [100, 101, 102, 103],
       [  2,   7,  12,  17],
       [  3,   8,  13,  18],
       [  4,   9,  14,  19]])

上書きしたい要素数に関係なく，値を一つだけ使えば，それで全ての要素を上書きできる．

In [48]:
x2[1] = 1000
x2

array([[ 100,    5,   10,   15],
       [1000, 1000, 1000, 1000],
       [   2,    7,   12,   17],
       [   3,    8,   13,   18],
       [   4,    9,   14,   19]])

最後の列だけを上書き

In [49]:
x2[:,-1] = np.arange(1000,1005)
x2

array([[ 100,    5,   10, 1000],
       [1000, 1000, 1000, 1001],
       [   2,    7,   12, 1002],
       [   3,    8,   13, 1003],
       [   4,    9,   14, 1004]])

#### 【問題１０】

x2の0行3列目の要素を99に上書き

### スライス

複数の行をスライス

In [50]:
x2[0:2]

array([[ 100,    5,   10, 1000],
       [1000, 1000, 1000, 1001]])

複数の列をスライス

In [51]:
x2[:,1:3]

array([[   5,   10],
       [1000, 1000],
       [   7,   12],
       [   8,   13],
       [   9,   14]])

#### 【問題１１】

x2から2~3行目の3列目をスライス