# NumPy：ユニバーサル関数と縮約関数

[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/rsimd/NITIC-HandsOnDeepLearning/blob/main/notebooks/numpy_ufunc.ipynb)

## NumPyのユニバーサル関数（ufunc）

NumPyには配列の各要素に同じ処理を高速に適用できる関数群があり，これをユニバーサル関数（ufunc）と呼ぶ．
ここでは代表的な ufunc として `np.log`, `np.exp`, `np.sin`, `np.cos`, `np.tan`, `np.floor`, `np.isnan` を紹介する．

In [3]:
import numpy as np

np.__version__

'2.4.4'

### `np.log`

`np.log` は自然対数（底 `e` の対数）を要素ごとに計算する関数である．
入力は正の値を使うのが基本である．

In [4]:
x = np.array([1, np.e, np.e**2, 10])
print("x:", x)
print("np.log(x):", np.log(x))

x: [ 1.          2.71828183  7.3890561  10.        ]
np.log(x): [0.         1.         2.         2.30258509]


### `np.exp`

`np.exp` は指数関数 `e^x` を要素ごとに計算する関数である．
`np.log` と逆の関係を持つため，組み合わせて使われることが多い．

In [5]:
y = np.array([-2, -1, 0, 1, 2])
print("y:", y)
print("np.exp(y):", np.exp(y))
print("np.log(np.exp(y)):", np.log(np.exp(y)))

y: [-2 -1  0  1  2]
np.exp(y): [0.13533528 0.36787944 1.         2.71828183 7.3890561 ]
np.log(np.exp(y)): [-2. -1.  0.  1.  2.]


### `np.sin`, `np.cos`, `np.tan`

三角関数も ufunc として提供されており，ラジアン単位の角度に対して要素ごとに計算される．
角度（度）を扱いたい場合は `np.deg2rad` でラジアンへ変換してから使うのが分かりやすい．

In [6]:
angles_deg = np.array([0, 30, 45, 60, 90])
angles_rad = np.deg2rad(angles_deg)

print("angles_deg:", angles_deg)
print("angles_rad:", angles_rad)
print("np.sin(angles_rad):", np.sin(angles_rad))
print("np.cos(angles_rad):", np.cos(angles_rad))
print("np.tan(angles_rad):", np.tan(angles_rad))

angles_deg: [ 0 30 45 60 90]
angles_rad: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
np.sin(angles_rad): [0.         0.5        0.70710678 0.8660254  1.        ]
np.cos(angles_rad): [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
np.tan(angles_rad): [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


### `np.floor`

`np.floor` は小数を含む値を，値以下の最大の整数へ切り下げる関数である．
なお，`np.floow` という関数は存在せず，正しくは `np.floor` である．

In [7]:
z = np.array([-1.8, -0.2, 0.0, 1.2, 3.9])
print("z:", z)
print("np.floor(z):", np.floor(z))

z: [-1.8 -0.2  0.   1.2  3.9]
np.floor(z): [-2. -1.  0.  1.  3.]


### `np.isnan`

`np.isnan` は要素が `NaN`（Not a Number）かどうかを判定し，真偽値の配列を返す関数である．
欠損値を含むデータの前処理でよく使われる．

In [8]:
w = np.array([0.0, np.nan, 1.5, np.nan, -3.0])
print("w:", w)
print("np.isnan(w):", np.isnan(w))
print("NaNを除いた要素:", w[~np.isnan(w)])

w: [ 0.   nan  1.5  nan -3. ]
np.isnan(w): [False  True False  True False]
NaNを除いた要素: [ 0.   1.5 -3. ]


### 【問題1】ニューラルネットワークでよく使われるsigmoid関数をNumPyで実装してみよう．


$$
\operatorname{sigmoid}(x) = \frac{1}{1+\operatorname{exp}(-x)}
$$

In [10]:
def sigmoid(x):
    ...

### 【問題2】ニューラルネットワークでよく使われるsoftmax関数をNumPyで実装してみよう．

$$
\mathrm{softmax}(x_i)
= \frac{\exp(x_i)}{\sum_{j=1}^{K} \exp(x_j)}
\quad (i = 1, \dots, K)
$$

入力xはベクトルだとしてください．

In [ ]:
def softmax(x):
    ...

## Reduction（縮約）関数

reduction／集約関数：配列全体や軸方向をまとめる関数

### `np.sum`

In [12]:
X = np.array([
    [2.0, 1.0, 0.1],
    [0.5, 2.5, 1.0]
])

In [15]:
np.sum(X)

np.float64(7.1)

### axisについて

列ごとに計算，行ごとに計算ができるのが`axis` option．

```
X の形: (2, 3)

[[2.0, 1.0, 0.1],   ← 行 0
 [0.5, 2.5, 1.0]]   ← 行 1
   ↑    ↑    ↑
 列0  列1  列2
```

axis=0 縦方向（列ごと）に計算

In [ ]:
np.sum(X, axis=0) # Xの列の数は3だった．列ごとに合計を計算できるはず．

array([2.5, 3.5, 1.1])

In [20]:
np.sum(X, axis=1) # Xの行の数は2だった．行ごとに合計を計算できるはず．

array([3.1, 4. ])

### 最小値と最大値（`np.min`, `np.max`）

`np.min` は最小値，`np.max` は最大値を返す．
配列全体だけでなく `axis` を指定して行ごと・列ごとにも計算できる．

In [21]:
print("np.min(X):", np.min(X))
print("np.max(X):", np.max(X))
print("np.min(X, axis=0):", np.min(X, axis=0))
print("np.max(X, axis=1):", np.max(X, axis=1))

np.min(X): 0.1
np.max(X): 2.5
np.min(X, axis=0): [0.5 1.  0.1]
np.max(X, axis=1): [2.  2.5]


### 最大値・最小値のインデックス（`np.argmax`, `np.argmin`）

`np.argmax` は最大値をとる位置（インデックス）を返し，`np.argmin` は最小値をとる位置を返す．
`axis` を指定すると，行ごと・列ごとにインデックスを取得できる．

In [27]:
print("np.argmax(X):", np.argmax(X))
print("np.argmin(X):", np.argmin(X))
print("np.argmax(X, axis=0):", np.argmax(X, axis=0))
print("np.argmin(X, axis=1):", np.argmin(X, axis=1))

np.argmax(X): 5
np.argmin(X): 0
np.argmax(X, axis=0): [1 1 1]
np.argmin(X, axis=1): [0 0]


### 平均・分散・標準偏差（`np.mean`, `np.var`, `np.std`）

`np.mean` は平均，`np.var` は分散，`np.std` は標準偏差を返す．
データの中心とばらつきを把握するときに使う基本的な集約関数である．

In [22]:
print("np.mean(X):", np.mean(X))
print("np.var(X):", np.var(X))
print("np.std(X):", np.std(X))
print("np.mean(X, axis=0):", np.mean(X, axis=0))
print("np.std(X, axis=1):", np.std(X, axis=1))

np.mean(X): 1.1833333333333333
np.var(X): 0.6847222222222222
np.std(X): 0.8274794391537607
np.mean(X, axis=0): [1.25 1.75 0.55]
np.std(X, axis=1): [0.77602978 0.84983659]


### keepdims=True を付けると？

In [23]:
np.sum(X, axis=1, keepdims=True)

array([[3.1],
       [4. ]])

### ブロードキャスト

ブロードキャストとは
形（shape）の異なる配列同士の演算を行うときに、
NumPy が自動的に配列の形をそろえて計算してくれる仕組み

In [24]:
x = np.array([1, 2, 3])
x + 10

array([11, 12, 13])

上の計算では内部で，10 → [10, 10, 10] としてから要素ごとに足している。


では1次元x二次元の配列でも考えてみよう．

In [25]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

v = np.array([10, 20, 30])

X + v

array([[11, 22, 33],
       [14, 25, 36]])

Xとvは形状が違うが，ちゃんと計算できている．これはブロードキャストのおかげ．

```
v → [[10, 20, 30],
     [10, 20, 30]]
```
とみなされてから
```
X + v → [[11, 22, 33],
          [14, 25, 36]]
```
こういう計算が行われている．

計算したい二つの配列上がったときに，以下のどちらの条件に当てはまればブロードキャストしてくれる．
1. 次元サイズが同じ
2. どちらかが 1

「各行に対する値」が 列として残るようにできる．配列の形状はプログラムで計算するときに大切なので，これも覚えておこう．

### 【問題3】多次元配列に対応したsoftmax関数にオーバーフロー対策をつけてみよう．

■ softmax関数に入力されるxについて：
$$
\mathbf{X}
=
\begin{pmatrix}
x_{11} & x_{12} & \cdots & x_{1K} \\
x_{21} & x_{22} & \cdots & x_{2K} \\
\vdots & \vdots &        & \vdots \\
x_{N1} & x_{N2} & \cdots & x_{NK}
\end{pmatrix}
\in \mathbb{R}^{N \times K}
$$

*   **行**：1つのサンプル
*   **列**：特徴の数

■ つまりsoftmaxの要素ごとの定義は：  

$$
\mathrm{softmax}(\mathbf{X})_{i k}
=
\frac{\exp(x_{ik})}
{\sum_{j=1}^{K} \exp(x_{ij})}
\quad
(i = 1,\dots,N,\; k = 1,\dots,K)
$$

* **各行ごとに** softmax が適用される  
* 行ごとに確率の和は 1

■ 数値安定化込みの場合は：

各サンプル $i$ ごとに最大値を引く：

$$
m_i = \max_{1 \le j \le K} x_{ij}
$$

$$
\mathrm{softmax}(\mathbf{X})_{i k}
=
\frac{\exp(x_{ik} - m_i)}
{\sum_{j=1}^{K} \exp(x_{ij} - m_i)}
$$

In [28]:
def softmax(x):
    # 入力xはデータ数 $\times$ 特徴数 の配列や，データ数  $\times$ ... $\times$ 特徴数の配列です．xと同じ形状の配列を返してください．
    ...